#ifndef SAMP12_4SHARELIBFUNC_GLOBAL_H
#define SAMP12_4SHARELIBFUNC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAMP12_4SHARELIBFUNC_LIBRARY)
#  define SAMP12_4SHARELIBFUNCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAMP12_4SHARELIBFUNCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAMP12_4SHARELIBFUNC_GLOBAL_H
